[2025-02-17T22:11:31.618+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T22:11:31.734+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_spotify_audiobooks.insert_book_data manual__2025-02-17T22:06:26.234646+00:00 [queued]>
[2025-02-17T22:11:31.740+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_spotify_audiobooks.insert_book_data manual__2025-02-17T22:06:26.234646+00:00 [queued]>
[2025-02-17T22:11:31.740+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-17T22:11:31.748+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_book_data> on 2025-02-17 22:06:26.234646+00:00
[2025-02-17T22:11:31.757+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=418) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-17T22:11:31.759+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_spotify_audiobooks', 'insert_book_data', 'manual__2025-02-17T22:06:26.234646+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/ExtractFromApi.py', '--cfg-path', '/tmp/tmpvh0055p5']
[2025-02-17T22:11:31.760+0000] {standard_task_runner.py:72} INFO - Started process 419 to run task
[2025-02-17T22:11:31.760+0000] {standard_task_runner.py:105} INFO - Job 186: Subtask insert_book_data
[2025-02-17T22:11:31.786+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_spotify_audiobooks.insert_book_data manual__2025-02-17T22:06:26.234646+00:00 [running]> on host 1d25279fc7fb
[2025-02-17T22:11:31.814+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_spotify_audiobooks' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T22:06:26.234646+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-17T22:06:26.234646+00:00'
[2025-02-17T22:11:31.815+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-17T22:11:31.815+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-17T22:11:31.815+0000] {logging_mixin.py:190} INFO - Current task name:insert_book_data state:running start_date:2025-02-17 22:11:31.735282+00:00
[2025-02-17T22:11:31.815+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_spotify_audiobooks and current dag run status:running
[2025-02-17T22:11:31.815+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-17T22:11:31.822+0000] {base.py:84} INFO - Retrieving connection 'audibooks_connection'
[2025-02-17T22:11:31.822+0000] {sql.py:186} WARNING - This setter is for backward compatibility and should not be used.
Since the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.
* apache-***-providers-mysql<5.7.1
* apache-***-providers-elasticsearch<5.5.1
* apache-***-providers-postgres<5.13.0
[2025-02-17T22:11:31.824+0000] {sql.py:511} INFO - Running statement: 
    INSERT INTO audiobooks (id, description, chapter_number, duration_ms, images, release_date, release_date_precision, available_markets)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    , parameters: ('73ThiUvDp7VbVX6tWTNjE4', '', 0, 60056, '[{"height": 640, "width": 640, "url": "https://i.scdn.co/image/ab676663000022a8706d7d39148810e742cef314"}, {"height": 300, "width": 300, "url": "https://i.scdn.co/image/ab6766630000db5b706d7d39148810e742cef314"}, {"height": 64, "width": 64, "url": "https://i.scdn.co/image/ab6766630000703b706d7d39148810e742cef314"}]', '2007-05-29', 'day', ['AT', 'AU', 'CA', 'CH', 'DE', 'GB', 'IE', 'NZ', 'PR', 'US'])
[2025-02-17T22:11:31.825+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ExtractFromApi.py", line 79, in insert_book_data_into_postgres
    postgres_hook.run(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "audiobooks_pkey"
DETAIL:  Key (id)=(73ThiUvDp7VbVX6tWTNjE4) already exists.

[2025-02-17T22:11:31.829+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-17T22:11:31.829+0000] {logging_mixin.py:190} INFO - Task start:2025-02-17 22:11:31.735282+00:00 end:2025-02-17 22:11:31.829111+00:00 duration:0.093829
[2025-02-17T22:11:31.829+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_book_data> dag:<DAG: fetch_and_store_spotify_audiobooks> dagrun:<DagRun fetch_and_store_spotify_audiobooks @ 2025-02-17 22:06:26.234646+00:00: manual__2025-02-17T22:06:26.234646+00:00, state:running, queued_at: 2025-02-17 22:06:26.250406+00:00. externally triggered: True>
[2025-02-17T22:11:31.829+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "audiobooks_pkey"
DETAIL:  Key (id)=(73ThiUvDp7VbVX6tWTNjE4) already exists.
[2025-02-17T22:11:31.830+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fetch_and_store_spotify_audiobooks, task_id=insert_book_data, run_id=manual__2025-02-17T22:06:26.234646+00:00, execution_date=20250217T220626, start_date=20250217T221131, end_date=20250217T221131
[2025-02-17T22:11:31.838+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-17T22:11:31.839+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 186 for task insert_book_data (duplicate key value violates unique constraint "audiobooks_pkey"
DETAIL:  Key (id)=(73ThiUvDp7VbVX6tWTNjE4) already exists.
; 419)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ExtractFromApi.py", line 79, in insert_book_data_into_postgres
    postgres_hook.run(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "audiobooks_pkey"
DETAIL:  Key (id)=(73ThiUvDp7VbVX6tWTNjE4) already exists.

[2025-02-17T22:11:31.861+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-17T22:11:31.870+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T22:11:31.871+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
